### ISSUE TITLE
Using mask with 0

### ISSUE THREAD

**Issue by aozen** [paulhodel/jtools#3]
Hello, there is a UK Phone +44 0000 000 000 mask in there. 
When we start typing it adds +44 auto, its cool. But i want to add +40 for example. When i start with "3" it must "+40 3", in this case it becomes "+43" how can i use 0 in phone format. Also how can i "a" in string masks. Thanks in advance.

**Comment by paulhodel** [comment]
Hi, I am going to create an option to scape the "0" and the other mask symbols. So, you will be able to achieve that soon. I will let you as soon as available in the repository.

**Comment by paulhodel** [comment]
You can use \a and \0 in the mask now.

<input type="text" data-mask="+4\0 000 0000 000">

Result: +40 and any number
